file_format: "1"
id: arkenswoop
name: arkenswoop
type: shield
url: https://github.com/SuperFola/arkenswoop
requires: [pro_micro]
exposes: [nice_view_header]
features:
  - keys
  - encoder
siblings:
  - arkenswoop_central
  - arkenswoop_left
  - arkenswoop_right
