manifest:
  remotes:
    - name: gibking
      url-base: https://github.com/gibking
  projects:
    - name: zmk
      remote: gibking
      revision: main
      import: app/west.yml
  self:
    path: config
